project_id = "pavibobervhqkfzwkotw"

[functions.send-email]
verify_jwt = false

[functions.process-refund]
verify_jwt = false

[functions.invite-admin]
verify_jwt = false

[functions.accept-admin-invite]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.upload-psw-document]
verify_jwt = false

[functions.register-psw]
verify_jwt = false

[functions.create-booking]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.mass-email-psws]
verify_jwt = false

[functions.notify-psws]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-psw-assignment-email]
verify_jwt = false

[functions.send-order-updated-email]
verify_jwt = false

[functions.send-order-cancelled-email]
verify_jwt = false

[functions.send-admin-order-alert]
verify_jwt = false

[functions.send-booking-confirmation-email]
verify_jwt = false

[functions.send-payment-success-email]
verify_jwt = false

[functions.send-completion-email]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = false

[functions.send-care-sheet-email]
verify_jwt = false

[functions.send-psw-reassigned-email]
verify_jwt = false

[functions.send-rebook-nudge-email]
verify_jwt = false

