// Content templates for the expanded city+service SEO layer.
// Each entry drives ExpandedCityServicePage. Keys must match the service slug
// used in expandedCityServiceRoutes.ts. Strictly ADDITIVE — do not remove keys.

export interface ExpandedServiceContent {
  label: string;
  category: "companion" | "condition" | "recovery" | "personal-care" | "aging" | "hire" | "urgent" | "specialty";
  heroDesc: string;
  intro: string;
  detail: string;
  bullets: string[];
  faqs: { question: string; answer: string }[];
}

const CONTACT_LINE = "Book online in under 2 minutes or call our care team — same-day availability, no contracts, no agency markup.";

export const EXPANDED_SERVICE_CONTENT: Record<string, ExpandedServiceContent> = {
  "companion-care": {
    label: "Companion Care",
    category: "companion",
    heroDesc: "Compassionate companion care from vetted personal support workers. Conversation, hobbies, meal-time company and light household help — starting at $35/hr.",
    intro: "Companion care focuses on reducing loneliness and keeping seniors socially engaged. Our PSWs share conversation, join in favourite hobbies, take walks and provide reassuring presence throughout the day.",
    detail: "Isolation is one of the biggest health risks facing older adults. A regular companion caregiver improves mood, cognition and appetite while giving family members peace of mind that a trained professional is checking in.",
    bullets: [
      "Friendly conversation, reminiscence and social engagement",
      "Board games, puzzles, reading and hobbies",
      "Accompaniment to appointments, errands and community outings",
      "Light meal preparation and shared meals",
      "Medication and hydration reminders",
      "Safety supervision without being intrusive",
    ],
    faqs: [
      { question: "What is companion care?", answer: "Companion care is non-medical support focused on social interaction, engagement and light daily tasks — helping seniors stay connected and active at home." },
      { question: "How is companion care different from personal care?", answer: "Companion care does not include hands-on personal tasks like bathing or toileting. If those are needed, we can pair companion care with personal support in the same visit." },
      { question: "How many hours of companion care can I book?", answer: "Any amount — a few hours a week, daily visits or full-day support. There are no minimums and no long-term contracts." },
    ],
  },
  "companion-services": {
    label: "Companion Services",
    category: "companion",
    heroDesc: "Reliable companion services for seniors — friendly visits, outings and meaningful time together with a vetted PSW.",
    intro: "Our companion services keep older adults socially engaged and safely supervised without the clinical feel of medical home care.",
    detail: "Regular companion visits reduce loneliness, encourage healthier routines and provide families with dependable reports on how their loved one is doing.",
    bullets: [
      "Weekly or daily social visits",
      "Errands, groceries and pharmacy runs",
      "Escort to appointments and events",
      "Light housekeeping and meal company",
      "Wellness reminders and check-ins",
    ],
    faqs: [
      { question: "Are companion services covered by OHIP?", answer: "Companion services are private-pay in Ontario. Some insurance plans and veterans programs may reimburse a portion of the cost." },
      { question: "Can I have the same companion each visit?", answer: "Yes — consistency is important for seniors. We do our best to schedule the same PSW for recurring visits so relationships can grow." },
    ],
  },
  "senior-companion": {
    label: "Senior Companion",
    category: "companion",
    heroDesc: "A trusted senior companion for your loved one. Friendly, patient and dependable PSWs providing social support and safety.",
    intro: "A senior companion visits regularly to keep an older adult engaged, safe and connected — sharing meals, hobbies and outings.",
    detail: "Loneliness is now recognized as a serious health risk. A regular senior companion adds structure, joy and a caring set of eyes on your loved one's wellbeing.",
    bullets: [
      "Warm one-on-one companionship",
      "Meal preparation and shared meals",
      "Community outings, walks and events",
      "Reading, memory games and hobbies",
      "Regular family updates on wellbeing",
    ],
    faqs: [
      { question: "How do I find a senior companion?", answer: "Book online through PSW Direct — you'll be matched with a vetted companion in your area, usually within hours." },
      { question: "What qualifications do senior companions have?", answer: "All companions are certified PSWs with credential verification, government ID and police background checks on file." },
    ],
  },
  "family-caregiver-relief": {
    label: "Family Caregiver Relief",
    category: "companion",
    heroDesc: "Give yourself a break. Trusted PSWs step in so family caregivers can rest, work or handle life — same-day availability.",
    intro: "Caring for a loved one is rewarding but exhausting. Family caregiver relief lets a vetted PSW take over for a few hours, an overnight or a weekend so you can recharge.",
    detail: "Regular respite protects the caregiver's health and reduces burnout. Even a short break each week can dramatically improve both the caregiver's and the care recipient's quality of life.",
    bullets: [
      "Same-day and scheduled respite blocks",
      "Overnight relief so you can sleep",
      "Weekend and vacation coverage",
      "Full continuity of the routine your loved one is used to",
      "Detailed care sheet after every shift",
    ],
    faqs: [
      { question: "How much notice do I need to give?", answer: "None required — same-day bookings are common. For overnight or vacation blocks, a few days notice helps us match the best caregiver." },
      { question: "Will the PSW follow the routine I've set up?", answer: "Yes. You provide the routine, medications and preferences at booking and the PSW documents everything in the care sheet." },
    ],
  },
  "memory-care": {
    label: "Memory Care",
    category: "condition",
    heroDesc: "Specialized in-home memory care for seniors with dementia, Alzheimer's or cognitive decline. Trained PSWs, from $35/hr.",
    intro: "Memory care focuses on safety, routine and dignity for seniors experiencing cognitive change. Our PSWs are trained in redirection, communication and behavioural strategies.",
    detail: "Staying in a familiar home environment is one of the strongest anchors for someone with memory loss. Trained in-home caregivers preserve routine, reduce agitation and help families avoid or delay a move to a facility.",
    bullets: [
      "Structured daily routines and cueing",
      "Wandering prevention and safety supervision",
      "Redirection techniques and calming approaches",
      "Personal care support with dignity",
      "Meal, hydration and medication reminders",
      "Family updates and behaviour notes",
    ],
    faqs: [
      { question: "Are your PSWs trained in memory care?", answer: "Many of our PSWs have specialized dementia and Alzheimer's training. Let us know your loved one's stage and we'll match an experienced caregiver." },
      { question: "Can memory care be provided overnight?", answer: "Yes — overnight memory care is one of our most requested services. It helps prevent nighttime wandering and gives family caregivers real rest." },
    ],
  },
  "parkinsons-care": {
    label: "Parkinson's Care",
    category: "condition",
    heroDesc: "In-home Parkinson's care from vetted PSWs — mobility support, medication timing, fall prevention and personal care.",
    intro: "Parkinson's disease affects movement, balance and daily routine. Our PSWs help clients stay steady, on schedule with medication and confident at home.",
    detail: "Consistency matters with Parkinson's — timed medications, gentle mobility support and reducing fall risk all improve quality of life. We tailor visits to the client's on/off cycles.",
    bullets: [
      "Medication timing reminders",
      "Safe transfers and gait support",
      "Fall prevention and home safety review",
      "Assistance with bathing, dressing and grooming",
      "Meal preparation and hydration",
      "Companion support during off periods",
    ],
    faqs: [
      { question: "Can a PSW help with Parkinson's medication?", answer: "PSWs cannot administer medication but can give timely reminders and observe for changes. Family or a nurse manages actual doses." },
      { question: "How often should I book Parkinson's care?", answer: "Even a few visits a week can help — many families start with morning and evening blocks to cover the highest-risk times of day." },
    ],
  },
  "stroke-recovery-care": {
    label: "Stroke Recovery Care",
    category: "recovery",
    heroDesc: "Support recovery at home after a stroke. Vetted PSWs assist with mobility, personal care and daily routines during rehabilitation.",
    intro: "The weeks after a stroke are critical. In-home stroke recovery care helps clients regain independence safely while preventing setbacks like falls and pressure sores.",
    detail: "Our PSWs work alongside your rehab team, encourage prescribed exercises, and provide the physical assistance and supervision families cannot always manage alone.",
    bullets: [
      "Safe transfers and mobility support",
      "Encouragement of prescribed rehab exercises",
      "Personal care with one-sided weakness accommodation",
      "Meal preparation and swallowing precautions",
      "Medication reminders and observation",
      "Fall prevention and home safety",
    ],
    faqs: [
      { question: "How soon after a stroke can we book care?", answer: "Right away. Many families book stroke recovery care the same day of hospital discharge to ensure a safe transition home." },
      { question: "Will you coordinate with our rehab therapists?", answer: "Yes — our PSWs document observations in a care sheet each shift so your therapy team stays informed." },
    ],
  },
  "palliative-home-care": {
    label: "Palliative Home Care",
    category: "specialty",
    heroDesc: "Compassionate palliative home care for individuals with serious illness — comfort, dignity and family support at home.",
    intro: "Palliative home care focuses on comfort, symptom management and quality of life. Our PSWs partner with your medical team and family to keep your loved one comfortable at home.",
    detail: "Trained palliative caregivers help with personal care, positioning, hydration reminders and emotional presence — while also giving exhausted family members essential relief.",
    bullets: [
      "Gentle personal care and positioning",
      "Skin care and pressure-sore prevention",
      "Hydration and comfort measures",
      "Emotional presence for client and family",
      "Overnight and 24-hour options",
      "Family respite so loved ones can rest",
    ],
    faqs: [
      { question: "Is palliative care the same as hospice?", answer: "Palliative care applies at any stage of serious illness; hospice care is a subset focused on end-of-life. Our PSWs support both." },
      { question: "Can you provide 24-hour palliative care?", answer: "Yes — 24-hour rotations are one of the most common palliative arrangements and often prevent an unwanted hospital transfer." },
    ],
  },
  "end-of-life-care": {
    label: "End-of-Life Care",
    category: "specialty",
    heroDesc: "Gentle end-of-life care at home from vetted PSWs. Comfort, dignity and family support during the most important time.",
    intro: "End-of-life care brings compassionate support into the home so your loved one can be surrounded by family. Our PSWs handle personal care and comfort measures with quiet respect.",
    detail: "We coordinate with hospice nurses and physicians, provide overnight vigils, and give exhausted family members space to be present as loved ones rather than caregivers.",
    bullets: [
      "24-hour and overnight coverage",
      "Positioning, mouth care and comfort measures",
      "Gentle personal care with maximum dignity",
      "Family respite so loved ones can be present",
      "Emotional and spiritual presence",
      "Coordination with hospice and physicians",
    ],
    faqs: [
      { question: "How quickly can end-of-life care start?", answer: "Same-day. Families often book urgently when hospice needs are identified — we prioritize these requests." },
      { question: "Do PSWs replace hospice nurses?", answer: "No — we work alongside hospice nurses. PSWs cover the hours and hands-on care that nurses cannot provide continuously." },
    ],
  },
  "personal-care-assistance": {
    label: "Personal Care Assistance",
    category: "personal-care",
    heroDesc: "Compassionate personal care assistance from vetted PSWs — bathing, dressing, grooming and hygiene with dignity.",
    intro: "Personal care assistance covers the daily tasks that become difficult as we age or recover from illness — always delivered with respect and privacy.",
    detail: "Our PSWs are trained in safe transfers and modest personal care techniques. We adapt to your loved one's preferences, pace and dignity every visit.",
    bullets: [
      "Bathing, showering and sponge baths",
      "Dressing, grooming and oral care",
      "Toileting and incontinence support",
      "Safe transfers and repositioning",
      "Skin care and pressure-sore prevention",
      "Medication reminders",
    ],
    faqs: [
      { question: "Can I book personal care for just a shower?", answer: "Yes — many families book short shower visits several times a week. Book by the hour with no minimum." },
      { question: "Will the same PSW come every time?", answer: "We aim for continuity. Once you find a PSW you're comfortable with, we prioritize booking them for future visits." },
    ],
  },
  "bathing-assistance": {
    label: "Bathing Assistance",
    category: "personal-care",
    heroDesc: "Safe, dignified bathing assistance from vetted PSWs. Prevent falls, protect skin health and preserve independence.",
    intro: "Bathing is one of the highest-risk activities in the home for older adults. Trained bathing assistance reduces falls while preserving dignity and comfort.",
    detail: "Our PSWs help with showers, tub baths, sponge baths and hair washing — using safe transfer techniques and honouring the client's preferences.",
    bullets: [
      "Shower and tub bath assistance",
      "Bed baths for those with limited mobility",
      "Hair washing and grooming",
      "Skin inspection and moisturizing",
      "Safe transfer in and out of the bathroom",
    ],
    faqs: [
      { question: "How often should a senior bathe?", answer: "Two to three full baths per week is generally sufficient for most seniors, with sponge baths and hygiene checks between." },
      { question: "Can bathing be done if my parent refuses?", answer: "Yes — our PSWs are trained in gentle approaches and cueing. Refusal is common with dementia, and there are proven techniques that work." },
    ],
  },
  "dressing-assistance": {
    label: "Dressing Assistance",
    category: "personal-care",
    heroDesc: "Patient dressing assistance from vetted PSWs — supportive, dignified help getting ready for the day.",
    intro: "Dressing becomes difficult with mobility limitations, arthritis or cognitive change. Our PSWs help clients start and end their day comfortably.",
    detail: "We follow the client's preferences on clothing, take care with buttons and fasteners, and use adaptive techniques for one-sided weakness or joint pain.",
    bullets: [
      "Morning dressing and evening changing",
      "Assistance with buttons, zippers and shoes",
      "Adaptive techniques for limited mobility",
      "Coordination with laundry and wardrobe organization",
      "Skin checks during changes",
    ],
    faqs: [
      { question: "Do you provide dressing help for men and women?", answer: "Yes. When gender preference matters (bathing, toileting, dressing), let us know at booking and we'll match accordingly." },
      { question: "Can dressing be combined with other tasks?", answer: "Absolutely — most visits include dressing plus bathing, breakfast prep and medication reminders in a single block." },
    ],
  },
  "toileting-assistance": {
    label: "Toileting Assistance",
    category: "personal-care",
    heroDesc: "Discreet toileting assistance from vetted PSWs — dignity, safety and hygiene in every visit.",
    intro: "Toileting and incontinence care are among the most sensitive tasks in home care. Our PSWs handle them with maximum respect and privacy.",
    detail: "We assist with safe bathroom transfers, incontinence product changes, skin care and cleanup — helping preserve independence and preventing skin breakdown.",
    bullets: [
      "Safe transfers to and from the toilet",
      "Incontinence brief and pad changes",
      "Perineal care and skin protection",
      "Commode and catheter emptying (non-clinical)",
      "Discreet, respectful handling",
    ],
    faqs: [
      { question: "Is toileting help covered in a regular visit?", answer: "Yes — toileting is part of personal care and is included in the hourly rate. No extra fee." },
      { question: "Can PSWs manage catheters?", answer: "PSWs can empty and clean external catheter bags and monitor for issues. Insertion and complex catheter care require a nurse." },
    ],
  },
  "hygiene-assistance": {
    label: "Hygiene Assistance",
    category: "personal-care",
    heroDesc: "Daily hygiene assistance from vetted PSWs — oral care, grooming, hand and skin care with respect.",
    intro: "Good hygiene protects health, comfort and confidence. Our PSWs support the daily grooming routines that keep seniors feeling like themselves.",
    detail: "We help with oral care, shaving, nail cleaning, hair brushing and skin moisturizing — while also monitoring for skin issues that need attention.",
    bullets: [
      "Oral care, denture cleaning and mouth checks",
      "Shaving and grooming",
      "Nail cleaning and hand care",
      "Hair brushing and styling",
      "Skin moisturizing and inspection",
    ],
    faqs: [
      { question: "Do PSWs cut nails?", answer: "PSWs file and clean nails but do not cut nails for diabetic clients — a foot-care nurse is the safe choice there." },
      { question: "How long does a hygiene visit take?", answer: "A focused hygiene visit is typically one to two hours; many families combine it with bathing and breakfast." },
    ],
  },
  "senior-assistance": {
    label: "Senior Assistance",
    category: "aging",
    heroDesc: "General senior assistance from vetted PSWs — daily living support, errands, housekeeping and companionship at home.",
    intro: "Senior assistance covers the mix of practical help older adults need to stay independent — from meal prep to errands to companionship.",
    detail: "Every senior's needs are different. We tailor visits to what actually matters — sometimes personal care, sometimes conversation, sometimes just running errands.",
    bullets: [
      "Meal preparation and grocery shopping",
      "Light housekeeping and laundry",
      "Errands and pharmacy runs",
      "Companionship and reassurance",
      "Personal care when needed",
      "Medication and appointment reminders",
    ],
    faqs: [
      { question: "What does senior assistance cost?", answer: "Starting at $35/hr with no minimums or contracts through PSW Direct — significantly less than agency alternatives." },
      { question: "Can we adjust visits over time?", answer: "Yes — increase, decrease or change visits any week. There's no commitment to a plan." },
    ],
  },
  "help-for-seniors": {
    label: "Help for Seniors",
    category: "aging",
    heroDesc: "Practical, compassionate help for seniors at home. Personal care, housekeeping, companionship and more from vetted PSWs.",
    intro: "Whether it's a helping hand for a few hours a week or full daily support, our PSWs help seniors stay comfortable and independent.",
    detail: "Families often start with a couple of hours a week and expand as needs change. Our flexible, no-contract model makes that easy.",
    bullets: [
      "Personal care and hygiene",
      "Meal preparation and grocery shopping",
      "Light housekeeping and laundry",
      "Companion visits and outings",
      "Medication reminders",
      "Escort to doctor's appointments",
    ],
    faqs: [
      { question: "How do I start help for a senior parent?", answer: "Book a first visit online — a vetted PSW will meet your parent, learn the routine, and we adjust from there." },
      { question: "Can I stop services anytime?", answer: "Yes — there are no contracts. Cancel or change any time." },
    ],
  },
  "aging-in-place": {
    label: "Aging in Place",
    category: "aging",
    heroDesc: "Aging in place support to help seniors stay safely at home. Personal care, mobility and daily help from vetted PSWs.",
    intro: "Most older adults want to stay in the home they love. Our in-home caregivers make aging in place practical, safe and dignified.",
    detail: "We provide the daily help that would otherwise force a move to a facility — often for a fraction of the cost — while preserving independence and routine.",
    bullets: [
      "Personal care and hygiene support",
      "Meal preparation and nutrition",
      "Medication reminders",
      "Housekeeping and errands",
      "Fall prevention and safety supervision",
      "Companionship and community connection",
    ],
    faqs: [
      { question: "Is aging in place cheaper than a nursing home?", answer: "Often yes — private retirement homes run $4,000-$8,000/month while a few hours of daily PSW support can be far less." },
      { question: "How do I know if aging in place is right?", answer: "Consider mobility, cognition, safety and social connection. A home care assessment can help — book a visit and our PSW will report back." },
    ],
  },
  "independent-living-support": {
    label: "Independent Living Support",
    category: "aging",
    heroDesc: "Independent living support from vetted PSWs — daily help that lets seniors stay in charge of their own home.",
    intro: "Independent living support fills the gaps that come with age or health changes so seniors can keep running their own home.",
    detail: "We support the client's own routine — not replace it. Errands, meals, hygiene help, transportation and companionship, delivered on their terms.",
    bullets: [
      "Personal care as needed",
      "Meal planning and preparation",
      "Errands and appointment escorts",
      "Light housekeeping",
      "Reminder systems for medication and appointments",
      "Companionship and outings",
    ],
    faqs: [
      { question: "How is this different from a nursing home?", answer: "Your loved one stays in their own home, keeps their routine and only pays for the hours they actually need." },
      { question: "Can support increase later if needed?", answer: "Yes — most families start light and add hours as needs change. Full 24-hour care is available when required." },
    ],
  },
  "private-caregiver": {
    label: "Private Caregiver",
    category: "hire",
    heroDesc: "Hire a private caregiver without the agency markup. Vetted PSWs from $35/hr with no contracts.",
    intro: "A private caregiver gives one-on-one attention that agency staff rotations rarely match. PSW Direct connects families directly with vetted caregivers.",
    detail: "You pay less because there is no agency overhead. The caregiver earns more because there is no middleman. Everyone wins — and consistency of care improves dramatically.",
    bullets: [
      "Direct connection with your caregiver",
      "Vetted credentials and background checks",
      "Transparent hourly rate — no surge fees",
      "GPS check-in and care documentation each shift",
      "No contracts, no minimum hours",
    ],
    faqs: [
      { question: "How is a private caregiver different from an agency?", answer: "No middleman. You pay less, the caregiver earns more, and you get consistency of care — often the same PSW every visit." },
      { question: "Are private caregivers insured?", answer: "Yes — PSW Direct maintains insurance coverage across every booked shift." },
    ],
  },
  "hire-a-caregiver": {
    label: "Hire a Caregiver",
    category: "hire",
    heroDesc: "Hire a vetted caregiver online in minutes. No contracts, no agency markup, same-day availability from $35/hr.",
    intro: "Hiring a caregiver used to mean weeks of agency intake, contracts and long minimums. PSW Direct makes it a two-minute booking.",
    detail: "Select your service, choose your schedule and we match you with a vetted PSW in your area — often the same day.",
    bullets: [
      "Two-minute online booking",
      "Same-day and next-day availability",
      "Vetted, background-checked caregivers",
      "Transparent hourly rate",
      "No contracts or minimums",
    ],
    faqs: [
      { question: "How fast can I hire a caregiver?", answer: "Often the same day. Simple requests are typically matched within hours." },
      { question: "Do I have to sign a contract?", answer: "No — every booking is by the hour. Cancel or change anytime." },
    ],
  },
  "hire-a-personal-support-worker": {
    label: "Hire a Personal Support Worker",
    category: "hire",
    heroDesc: "Hire a Personal Support Worker fast. Credential-verified PSWs available same-day across Ontario — starting at $35/hr.",
    intro: "PSW Direct is the fastest way to hire a certified Personal Support Worker in Ontario. All PSWs on our platform have verified credentials, police checks and government ID on file.",
    detail: "You skip agency waitlists, avoid long contracts and often get better continuity of care because you can rebook the same PSW every visit.",
    bullets: [
      "Certified Personal Support Workers only",
      "Verified credentials, ID and police checks",
      "Same-day availability across Ontario",
      "No agency fees or minimums",
      "GPS-tracked shifts and care documentation",
    ],
    faqs: [
      { question: "What qualifications do your PSWs hold?", answer: "All PSWs on PSW Direct have a recognized Ontario PSW certificate and a current police background check." },
      { question: "Can I request a specific PSW?", answer: "Yes — after a first visit you can rebook the same PSW directly through your client dashboard." },
    ],
  },
  "same-day-home-care": {
    label: "Same-Day Home Care",
    category: "urgent",
    heroDesc: "Same-day home care from vetted PSWs. Book online now and often receive care within hours.",
    intro: "Sometimes care is needed today — a fall, an early discharge, a caregiver who called in sick. Our same-day home care meets that moment.",
    detail: "We prioritize urgent bookings and dispatch the closest available PSW. Most same-day requests are matched within a few hours.",
    bullets: [
      "Urgent same-day dispatch",
      "Personal care, companionship and supervision",
      "Overnight and 24-hour coverage available",
      "GPS-tracked check-in on every shift",
      "Transparent hourly rate",
    ],
    faqs: [
      { question: "How fast is same-day care?", answer: "Many requests are matched within a few hours. Book online and we start dispatching immediately." },
      { question: "Is there a rush fee?", answer: "No surprise surge pricing. Same-day rates are the same as scheduled bookings." },
    ],
  },
  "urgent-home-care": {
    label: "Urgent Home Care",
    category: "urgent",
    heroDesc: "Urgent home care when you need it now — vetted PSWs available same-day for emergencies and unexpected care gaps.",
    intro: "Urgent home care covers the situations that don't wait — sudden hospital discharge, a fall, a caregiver no-show or a rapid change in condition.",
    detail: "PSW Direct's dispatch prioritizes urgent bookings. Book online and we start matching immediately.",
    bullets: [
      "Immediate dispatch to closest PSW",
      "Same-day and overnight coverage",
      "Personal care, supervision and companionship",
      "Care documentation on every shift",
      "No contracts or minimums",
    ],
    faqs: [
      { question: "What is considered urgent home care?", answer: "Any care need that can't wait — falls, discharge, caregiver gaps or rapid change in a senior's status." },
      { question: "Can urgent care continue as ongoing care?", answer: "Yes — many families start with urgent coverage and roll it into a regular weekly schedule once things stabilize." },
    ],
  },
  "weekend-home-care": {
    label: "Weekend Home Care",
    category: "urgent",
    heroDesc: "Weekend home care for seniors and recovering patients. Saturday and Sunday PSW coverage from $35/hr.",
    intro: "Weekend home care fills the gaps that agencies often can't cover — Saturday and Sunday shifts, holiday weekends and long-weekend respite for family caregivers.",
    detail: "Our PSWs are available seven days a week. Weekend rates are the same as weekday rates.",
    bullets: [
      "Saturday and Sunday coverage",
      "Long-weekend and holiday shifts",
      "Full-day and overnight blocks",
      "Personal care and companionship",
      "Family respite so you can rest",
    ],
    faqs: [
      { question: "Are weekend rates higher?", answer: "No — weekend and holiday hours are billed at the same rate as weekday hours." },
      { question: "Can weekend care become ongoing?", answer: "Yes — many families keep a recurring weekend block so the family caregiver has predictable time off." },
    ],
  },
  "recovery-care": {
    label: "Recovery Care",
    category: "recovery",
    heroDesc: "In-home recovery care after illness, hospital stay or surgery. Vetted PSWs support safe healing at home.",
    intro: "Recovery care bridges the gap between hospital discharge and full independence. Our PSWs handle personal care, mobility and daily routines while you focus on healing.",
    detail: "Studies show consistent in-home support after discharge reduces re-admission rates. Book by the hour, day or in overnight blocks.",
    bullets: [
      "Personal care and hygiene during recovery",
      "Safe transfers and mobility support",
      "Meal preparation and nutrition",
      "Medication reminders",
      "Wound and skin observation",
      "Fall prevention",
    ],
    faqs: [
      { question: "How long is recovery care typically needed?", answer: "It varies — many families book intensively for the first two weeks and taper down as strength returns." },
      { question: "Do PSWs replace home nursing?", answer: "No — for wound care, IV or injections you'll need a home care nurse. PSWs cover the daily hands-on care that nurses don't." },
    ],
  },
  "surgery-recovery-care": {
    label: "Surgery Recovery Care",
    category: "recovery",
    heroDesc: "Recover safely at home after surgery. Trained PSWs help with mobility, personal care and daily routine.",
    intro: "The first two weeks after surgery are the highest-risk period for falls and complications. Our surgery recovery care makes home the safest place to heal.",
    detail: "We assist with all the daily tasks that become hard after an operation — bathing, dressing, getting to the bathroom safely, and following the surgeon's activity restrictions.",
    bullets: [
      "Safe transfers within lifting restrictions",
      "Bathing and dressing help",
      "Meal preparation and hydration",
      "Medication reminders",
      "Observation for signs of complications",
      "Companionship during recovery",
    ],
    faqs: [
      { question: "When should recovery care start?", answer: "Ideally the day of discharge. Many families book PSWs to arrive at the same time the patient comes home." },
      { question: "How many hours per day are typical?", answer: "Most families book 4-8 hours per day the first week, tapering down as independence returns." },
    ],
  },
  "hip-replacement-recovery": {
    label: "Hip Replacement Recovery",
    category: "recovery",
    heroDesc: "In-home hip replacement recovery care from vetted PSWs. Safe transfers, personal care and rehab support.",
    intro: "Hip replacement recovery is smoother with hands-on help at home. Our PSWs assist within your surgeon's precautions and help you regain confidence.",
    detail: "We support prescribed exercises, use safe transfer techniques, help with bathing and dressing, and prevent the falls that can undo weeks of healing.",
    bullets: [
      "Safe transfers within hip precautions",
      "Assistance with bathing and dressing",
      "Encouragement of prescribed exercises",
      "Meal preparation and nutrition",
      "Medication reminders",
      "Fall prevention",
    ],
    faqs: [
      { question: "How long is hip replacement recovery?", answer: "Most patients regain independence within 6-8 weeks. In-home care is most valuable for the first 2-3 weeks." },
      { question: "Do you know hip precautions?", answer: "Yes — our PSWs are trained in standard hip precautions and adapt to your surgeon's specific instructions." },
    ],
  },
  "knee-replacement-recovery": {
    label: "Knee Replacement Recovery",
    category: "recovery",
    heroDesc: "In-home knee replacement recovery from vetted PSWs — safe mobility, personal care and rehab support.",
    intro: "Knee replacement recovery depends on consistent movement, safe transfers and pain management. Our PSWs help you stay on the plan.",
    detail: "We assist with prescribed exercises, ice and elevation routines, bathing, meal prep and the daily tasks that hurt to do alone.",
    bullets: [
      "Safe transfers and walker/crutch support",
      "Encouragement of prescribed exercises",
      "Bathing and dressing help",
      "Ice, elevation and comfort routines",
      "Meal preparation",
      "Fall prevention",
    ],
    faqs: [
      { question: "When should knee recovery care start?", answer: "Day of discharge is ideal. The first two weeks are when help matters most." },
      { question: "Can PSWs do the exercises with me?", answer: "Yes — PSWs encourage and supervise prescribed exercises but don't replace a physiotherapist." },
    ],
  },
  "arthritis-care": {
    label: "Arthritis Care",
    category: "condition",
    heroDesc: "In-home arthritis care from vetted PSWs — mobility support, personal care and daily help on the tough days.",
    intro: "Arthritis makes ordinary tasks painful. Our PSWs step in when hands, hips or knees make daily routines difficult.",
    detail: "We adapt to good days and bad days — helping with dressing, bathing, cooking and errands so your loved one keeps moving forward.",
    bullets: [
      "Adaptive dressing and bathing help",
      "Meal preparation and grocery shopping",
      "Light housekeeping and laundry",
      "Gentle mobility support",
      "Errands and appointment escorts",
    ],
    faqs: [
      { question: "How often should I book arthritis care?", answer: "Even a few visits a week can protect joints from overuse. Many clients book daily morning help." },
      { question: "Do PSWs help with joint injections or medications?", answer: "PSWs cannot administer injections but can give timely medication reminders and observe effects." },
    ],
  },
  "diabetes-care": {
    label: "Diabetes Care",
    category: "condition",
    heroDesc: "In-home diabetes care from vetted PSWs. Meal support, foot care checks and medication reminders for people living with diabetes.",
    intro: "Diabetes care at home focuses on the daily habits that keep blood sugar stable — meal timing, activity, foot inspection and medication reminders.",
    detail: "Our PSWs support diabetic-friendly meal preparation and daily routines. Insulin injection is a nursing task, but the surrounding routine is often what needs the most help.",
    bullets: [
      "Diabetic-friendly meal preparation",
      "Medication and blood-sugar-check reminders",
      "Foot inspection support",
      "Hygiene and skin care",
      "Companionship on activity",
    ],
    faqs: [
      { question: "Can PSWs administer insulin?", answer: "No — insulin injection is a nursing task. PSWs can remind and observe but cannot inject." },
      { question: "Can PSWs do foot care?", answer: "PSWs inspect and moisturize but do not trim diabetic toenails — a foot-care nurse handles that." },
    ],
  },
  "copd-home-care": {
    label: "COPD Home Care",
    category: "condition",
    heroDesc: "In-home COPD care from vetted PSWs — energy conservation, oxygen setup support and daily help with breathing challenges.",
    intro: "COPD makes daily tasks exhausting. Our PSWs use energy-conservation techniques and take over the physical work that leaves clients breathless.",
    detail: "We help with pacing, oxygen equipment reminders, meal preparation and personal care — all in ways that reduce shortness of breath.",
    bullets: [
      "Energy-conservation techniques",
      "Oxygen equipment reminders (no clinical setup)",
      "Bathing and dressing with paced rests",
      "Light housekeeping",
      "Meal preparation",
      "Companionship during exacerbations",
    ],
    faqs: [
      { question: "Can PSWs manage oxygen equipment?", answer: "PSWs cannot titrate oxygen but can remind clients to wear it and observe for symptoms." },
      { question: "How often should I book COPD care?", answer: "Daily morning help is common — mornings are typically the hardest for COPD clients." },
    ],
  },
  "cancer-home-care": {
    label: "Cancer Home Care",
    category: "condition",
    heroDesc: "Compassionate cancer home care from vetted PSWs during treatment and recovery — practical help and gentle support.",
    intro: "Cancer treatment is exhausting. In-home cancer care handles the daily tasks that become impossible during and after chemotherapy or radiation.",
    detail: "We coordinate with your cancer team, provide gentle personal care, prepare nutrition-focused meals and give family caregivers essential relief.",
    bullets: [
      "Personal care during low-energy periods",
      "Nutrition-focused meal preparation",
      "Medication reminders",
      "Light housekeeping and laundry",
      "Escort to treatment appointments",
      "Overnight support after difficult treatments",
    ],
    faqs: [
      { question: "Can you support treatment days?", answer: "Yes — many clients book PSWs on treatment days for escort and afterward for rest and hydration support." },
      { question: "Do you coordinate with the cancer clinic?", answer: "We document observations for your team but do not deliver clinical care. Home care nurses cover the clinical side." },
    ],
  },
  "multiple-sclerosis-care": {
    label: "Multiple Sclerosis Care",
    category: "condition",
    heroDesc: "In-home multiple sclerosis (MS) care from vetted PSWs — mobility, personal care and daily support that adapts to flare-ups.",
    intro: "MS symptoms vary day to day. Our PSWs adapt visits to good days and bad — from light companionship to full personal care during flare-ups.",
    detail: "We support fatigue management, safe transfers, personal care and daily routines while family caregivers focus on being family again.",
    bullets: [
      "Fatigue-friendly visit pacing",
      "Safe transfers and mobility support",
      "Personal care during flares",
      "Meal preparation and nutrition",
      "Medication reminders",
      "Companionship on isolating days",
    ],
    faqs: [
      { question: "Can PSWs help during MS flares?", answer: "Yes — we scale up hours during flares and back down when symptoms ease, with no contract changes required." },
      { question: "Are your PSWs familiar with MS?", answer: "Many are. Let us know your loved one's stage and mobility level and we match a PSW with the right experience." },
    ],
  },
  "als-care": {
    label: "ALS Care",
    category: "condition",
    heroDesc: "Compassionate in-home ALS care from vetted PSWs — personal care, mobility support and family respite for every stage.",
    intro: "ALS care evolves as the disease progresses. Our PSWs adapt each visit to what the client and family need most.",
    detail: "We handle personal care, transfers, feeding assistance and communication support while giving exhausted family caregivers essential breaks.",
    bullets: [
      "Personal care and hygiene",
      "Safe transfers and positioning",
      "Feeding and hydration support",
      "Communication accommodations",
      "Overnight and 24-hour coverage",
      "Family respite",
    ],
    faqs: [
      { question: "Can you provide 24-hour ALS care?", answer: "Yes — 24-hour coverage is a common ALS arrangement, often through rotating PSWs to ensure fresh, attentive care." },
      { question: "Do PSWs manage feeding tubes or vents?", answer: "PSWs cannot manage feeding tubes or ventilators — that's a nursing role. We handle the surrounding personal care and daily routines." },
    ],
  },
  "heart-failure-care": {
    label: "Heart Failure Care",
    category: "condition",
    heroDesc: "In-home heart failure care from vetted PSWs — daily weight and symptom monitoring reminders, meals and personal care.",
    intro: "Heart failure care at home focuses on the daily habits that prevent hospitalizations — weights, meal timing, activity pacing and medication reminders.",
    detail: "Our PSWs support the low-sodium meals, gentle activity and daily observations that heart failure programs recommend.",
    bullets: [
      "Low-sodium meal preparation",
      "Weight and symptom check reminders",
      "Medication reminders",
      "Gentle mobility support",
      "Personal care with rest breaks",
      "Companionship and reassurance",
    ],
    faqs: [
      { question: "Can PSWs check blood pressure?", answer: "PSWs can prompt and observe self-checks but don't provide clinical readings — a home nurse can visit for that." },
      { question: "How often should heart failure care be booked?", answer: "Daily morning visits are common — that's when weights and morning routines happen." },
    ],
  },

  // ─────────────────────────────────────────────────────────
  // Additive Phase 2: broader family-search service templates
  // Each key is unique — verified against existing route registries
  // (cityServiceRoutes, additionalCityServiceRoutes, privateHomeCareRoutes).
  // ─────────────────────────────────────────────────────────
  "home-care-for-seniors": {
    label: "Home Care for Seniors",
    category: "aging",
    heroDesc: "Home care for seniors from vetted personal support workers — personal care, meals, medication reminders and companionship. From $35/hr.",
    intro: "Home care for seniors keeps older adults safely and comfortably in the home they know. Our PSWs help with daily routines, personal care, meals and social engagement so seniors can stay independent longer.",
    detail: "Every senior is different. We match caregivers by personality, language and experience so the fit feels natural from day one. Care plans stay flexible and can scale up or down as needs change.",
    bullets: [
      "Personal care (bathing, dressing, toileting) with dignity",
      "Meal planning, preparation and shared meals",
      "Medication reminders and hydration prompts",
      "Companionship, hobbies and outings",
      "Fall prevention and safe mobility support",
      "Care sheets and family updates after every shift",
    ],
    faqs: [
      { question: "How much home care do seniors usually need?", answer: "Many families start with 2-4 hours a day, several days a week, and expand as needs grow. There are no minimums." },
      { question: "Can I request the same PSW every visit?", answer: "Yes — continuity of care is a priority. We schedule the same PSW whenever their availability allows." },
      { question: "Is home care safer than a retirement home?", answer: "For most seniors, home care offers one-on-one attention and familiar surroundings — often with better outcomes than shared facility care." },
    ],
  },
  "elder-care": {
    label: "Elder Care",
    category: "aging",
    heroDesc: "Compassionate elder care at home — daily support, personal care, companionship and safety supervision from vetted PSWs. From $35/hr.",
    intro: "Elder care through PSW Direct is professional, home-based support that helps aging parents live safely and with dignity. Every caregiver is credential-verified, police-checked and reviewed for compassion.",
    detail: "We build elder care plans around your loved one's routine — not around agency shift blocks. Book by the hour, adjust weekly, and add hours quickly if hospital or health events change what's needed.",
    bullets: [
      "Personal hygiene and grooming",
      "Meal preparation and feeding support",
      "Mobility and safe transfers",
      "Medication and appointment reminders",
      "Cognitive engagement and conversation",
      "Overnight and 24-hour options",
    ],
    faqs: [
      { question: "What does elder care include?", answer: "Personal care, meals, mobility support, medication reminders, companionship and safety supervision — all provided by trained PSWs in the client's home." },
      { question: "How is elder care different from a nursing home?", answer: "Elder care at home is one-on-one, in familiar surroundings, and often more affordable than private long-term-care facilities." },
      { question: "Can elder care include overnight coverage?", answer: "Yes — overnight and 24-hour shifts are available across Ontario, same-day when possible." },
    ],
  },
  "home-health-care": {
    label: "Home Health Care",
    category: "aging",
    heroDesc: "Home health care from certified PSWs — personal care, health observation, medication reminders and safe mobility support. From $35/hr.",
    intro: "Home health care through PSW Direct focuses on the daily, non-clinical support that keeps seniors and recovering adults healthy at home: hygiene, nutrition, mobility, medication reminders and vigilant observation.",
    detail: "Our PSWs observe and report — changes in appetite, mood, wounds, breathing or mobility — so families and clinicians catch issues early. For clinical tasks (injections, wound care), we coordinate with home nursing.",
    bullets: [
      "Personal care and hygiene",
      "Medication reminders and adherence support",
      "Vital-sign observation and reporting",
      "Nutrition and hydration monitoring",
      "Safe mobility and fall prevention",
      "Care documentation after every visit",
    ],
    faqs: [
      { question: "Is home health care the same as home nursing?", answer: "No. PSWs provide personal care and health observation; nurses provide clinical care (injections, wound care, IVs). We coordinate both when needed." },
      { question: "Does OHIP cover home health care?", answer: "OHIP funds a limited number of PSW hours through Ontario Health atHome; most families supplement with private-pay for reliable coverage." },
      { question: "Can home health care be booked same-day?", answer: "Yes — same-day PSW visits are available across most Ontario cities." },
    ],
  },
  "live-in-care": {
    label: "Live-In Care",
    category: "aging",
    heroDesc: "Live-in care with a dedicated PSW who provides around-the-clock support in the client's home — safety, personal care and companionship, 24/7.",
    intro: "Live-in care places a dedicated personal support worker in the client's home so support is available around the clock. It's the closest alternative to a retirement home while keeping the senior in their own environment.",
    detail: "Live-in schedules typically rotate between two or three PSWs so no single caregiver is on shift more than a safe number of hours. Clients get consistency; PSWs get sustainable rest.",
    bullets: [
      "24/7 in-home presence",
      "Personal care throughout the day",
      "Overnight safety and toileting support",
      "Meals, medication and household routines",
      "Consistent PSW rotation for continuity",
      "Detailed daily documentation",
    ],
    faqs: [
      { question: "How much does live-in care cost?", answer: "Live-in care is quoted per day and depends on the client's needs. It is typically less expensive than 24-hour hourly care and more affordable than private retirement homes." },
      { question: "Does the live-in PSW sleep at the home?", answer: "Yes — a bed and rest breaks are required. PSWs remain available for overnight needs but must have scheduled sleep periods." },
      { question: "Can families keep the same PSW long-term?", answer: "Yes — we match a small rotation of 2-3 PSWs to build continuity while ensuring safe rest and coverage." },
    ],
  },
  "home-support-services": {
    label: "Home Support Services",
    category: "aging",
    heroDesc: "Home support services for seniors and adults — personal care, meals, housekeeping and companionship from vetted PSWs. From $35/hr.",
    intro: "Home support services cover the daily tasks that become harder with age or illness — bathing, meals, tidying, medication reminders, transportation and companionship. Our PSWs bring compassion and consistency to every visit.",
    detail: "Home support is often the entry point to home care. Many families start with a few hours a week for meals and companionship and expand as needs evolve.",
    bullets: [
      "Bathing, dressing and hygiene support",
      "Meal preparation and feeding assistance",
      "Light housekeeping and laundry",
      "Grocery shopping and errands",
      "Escorts to appointments",
      "Companionship and safety checks",
    ],
    faqs: [
      { question: "What's included in home support services?", answer: "Non-medical support with daily living — personal care, meals, housekeeping, transportation, medication reminders and companionship." },
      { question: "Are home support services covered by insurance?", answer: "Some extended health benefits, veterans programs and long-term care insurance policies cover home support. We provide receipts formatted for claims." },
      { question: "How quickly can home support start?", answer: "Most Ontario bookings are matched with a PSW within hours; same-day starts are common." },
    ],
  },
  "senior-companion-care": {
    label: "Senior Companion Care",
    category: "companion",
    heroDesc: "Senior companion care — friendly visits, hobbies, meals and safety supervision from a vetted PSW. Reduce isolation and lift daily mood.",
    intro: "Senior companion care is regular one-on-one companionship that reduces loneliness and keeps older adults socially engaged. Our PSWs bring warmth, patience and structure to every visit.",
    detail: "Companionship is one of the most powerful forms of home care. Regular visits improve mood, appetite, sleep and cognition — and give families the peace of mind of consistent check-ins.",
    bullets: [
      "Friendly conversation and reminiscence",
      "Board games, puzzles, reading and hobbies",
      "Shared meals and light meal preparation",
      "Walks and community outings",
      "Medication and hydration reminders",
      "Family updates after each visit",
    ],
    faqs: [
      { question: "How often are companion visits usually booked?", answer: "Many families schedule 2-3 visits per week of 2-4 hours each. Others prefer daily short visits. There's no minimum." },
      { question: "Can I request a PSW who speaks my parent's language?", answer: "Yes — note the preference at booking and we'll match a language-appropriate caregiver." },
      { question: "Does companion care include personal care?", answer: "Companion visits can include light personal care support. If more hands-on personal care is needed, we schedule a full personal-care visit." },
    ],
  },
  "caregiver-services": {
    label: "Caregiver Services",
    category: "hire",
    heroDesc: "Caregiver services from vetted personal support workers — personal care, meals, companionship and safety supervision. From $35/hr, no contracts.",
    intro: "Caregiver services through PSW Direct give families direct access to vetted personal support workers without agency markup or long-term contracts. Book by the hour, adjust weekly.",
    detail: "Every caregiver is credential-verified, police-checked and reviewed for compassion. GPS check-in confirms every shift; a written care sheet closes it out.",
    bullets: [
      "Certified PSW credentials verified",
      "Police background check on file",
      "Government ID verified",
      "GPS check-in on every shift",
      "Care sheet documented and shared",
      "Same-day availability across Ontario",
    ],
    faqs: [
      { question: "How do I hire a caregiver?", answer: "Book online in under 2 minutes — enter your address, choose a schedule, and a vetted PSW is matched within hours." },
      { question: "Do caregivers sign a contract?", answer: "No contracts are required. Book by the hour with same-day cancellations up to 4 hours before the shift." },
      { question: "Can I choose my caregiver?", answer: "Yes — after your first booking, request the same PSW for future visits whenever their schedule allows." },
    ],
  },
  "personal-care-services": {
    label: "Personal Care Services",
    category: "personal-care",
    heroDesc: "Personal care services — bathing, dressing, toileting, mobility and hygiene support from certified PSWs. Dignified, private, in-home care.",
    intro: "Personal care services support the essential daily tasks that maintain hygiene, dignity and comfort. Our PSWs approach every visit with respect, privacy and gentle technique.",
    detail: "Personal care is our most-requested service. Whether it's daily morning routines or occasional support after surgery, we match a PSW with the right training and personality for the client.",
    bullets: [
      "Bathing, showering and sponge baths",
      "Dressing, grooming and oral care",
      "Toileting and incontinence support",
      "Safe transfers and repositioning",
      "Skin care and pressure-sore prevention",
      "Support with mobility aids",
    ],
    faqs: [
      { question: "Can I request a female PSW for personal care?", answer: "Yes — many clients prefer a same-gender caregiver for bathing and toileting. Note the preference at booking." },
      { question: "How long does a personal care visit take?", answer: "Most personal care visits are 1-2 hours. Longer visits can include personal care plus meals, medication reminders and companionship." },
      { question: "Are PSWs trained for incontinence care?", answer: "Yes — all PSWs are trained in dignified continence and skin care." },
    ],
  },
  "home-assistance": {
    label: "Home Assistance",
    category: "aging",
    heroDesc: "In-home assistance for seniors — personal care, meals, housekeeping and errands from vetted PSWs. Flexible, hourly, no contracts.",
    intro: "Home assistance covers the everyday tasks that make it possible to age well at home — from a warm morning routine to help with errands and evening wind-down.",
    detail: "We tailor home assistance to the client's day, not a template. That means the same PSW arriving at the same time, doing the tasks that matter most to the family — from a light breakfast to a bedtime medication reminder.",
    bullets: [
      "Morning and evening routines",
      "Meal preparation and clean-up",
      "Medication reminders",
      "Light housekeeping and laundry",
      "Errands and grocery runs",
      "Companionship and safety supervision",
    ],
    faqs: [
      { question: "How is home assistance different from home care?", answer: "It's the same category of support — 'home assistance' emphasises the daily-living side (meals, housekeeping, errands) alongside personal care." },
      { question: "Can home assistance be booked for just a few hours a week?", answer: "Yes — there are no minimums. Many families start with two 2-hour visits per week." },
      { question: "Do PSWs help with pet care?", answer: "Light pet duties (feeding, brief walks) can be included with client approval; PSWs are not professional pet caregivers." },
    ],
  },
  "daily-living-assistance": {
    label: "Daily Living Assistance",
    category: "aging",
    heroDesc: "Daily living assistance from vetted PSWs — help with bathing, dressing, meals, mobility and medication reminders. From $35/hr.",
    intro: "Daily living assistance (ADL support) helps clients complete the routine tasks that maintain independence — bathing, dressing, eating, toileting, mobility and grooming.",
    detail: "Our PSWs are trained in respectful ADL support with a focus on preserving dignity and encouraging independence. We do 'with' the client, not 'for' the client, wherever safely possible.",
    bullets: [
      "Bathing and personal hygiene",
      "Dressing and grooming",
      "Feeding and hydration support",
      "Toileting and continence care",
      "Safe transfers and mobility",
      "Grooming, oral care and skin checks",
    ],
    faqs: [
      { question: "What are ADLs?", answer: "Activities of Daily Living — bathing, dressing, feeding, toileting, transferring and continence. IADLs (meals, housekeeping, errands) are the next tier up." },
      { question: "Can PSWs handle both ADLs and IADLs?", answer: "Yes — most home-care shifts combine ADL support (personal care) with IADL support (meals, housekeeping)." },
      { question: "Do PSWs help with feeding tubes or catheters?", answer: "PSWs assist with feeding preparation and continence care; feeding tubes, wound care and catheterisation require home nursing." },
    ],
  },
  "medication-reminder-services": {
    label: "Medication Reminder Services",
    category: "aging",
    heroDesc: "Medication reminder services — timely prompts, safe hydration and observation from vetted PSWs. Reduce missed doses and hospitalisations.",
    intro: "Medication reminders are one of the highest-impact forms of home care. Missed or doubled doses are a leading cause of avoidable hospitalisation among seniors. Our PSWs prompt, observe and document — safely and consistently.",
    detail: "PSWs do not administer medications. They remind, verify the client took the correct dose from a properly labelled blister pack or dispenser, and report any concerns immediately.",
    bullets: [
      "Timed reminders (morning, noon, evening, bedtime)",
      "Blister pack and dispenser support",
      "Hydration prompts alongside doses",
      "Observation for side effects",
      "Refill and pharmacy coordination reminders",
      "Written care-sheet documentation of every dose",
    ],
    faqs: [
      { question: "Can PSWs administer medications?", answer: "No. PSWs prompt and observe medication taken by the client. Injection and medication administration require a home nurse." },
      { question: "How often should medication reminders be booked?", answer: "Match to the dosing schedule — many clients book brief morning + evening visits." },
      { question: "Can PSWs manage a blister pack?", answer: "Yes — they open the compartment, hand the medication to the client, verify it's taken and document it." },
    ],
  },
  "meal-preparation-services": {
    label: "Meal Preparation Services",
    category: "aging",
    heroDesc: "In-home meal preparation from vetted PSWs — healthy meals, dietary needs respected, shared with warmth. From $35/hr.",
    intro: "Meal preparation services keep clients well-nourished and hydrated with meals cooked to their taste, dietary needs and cultural preferences. Shared meals also fight isolation.",
    detail: "Malnutrition is a hidden risk for seniors living alone. A regular meal-prep visit — even once daily — reliably improves appetite, energy and mood.",
    bullets: [
      "Menu planning around preferences and diet",
      "Grocery shopping when requested",
      "Fresh meal preparation and portioning",
      "Freezer meals for future days",
      "Feeding assistance when needed",
      "Kitchen cleanup after meals",
    ],
    faqs: [
      { question: "Can PSWs cook to specific dietary needs?", answer: "Yes — diabetic, low-sodium, renal, cultural and religious diets are all supported. Share requirements at booking." },
      { question: "Can the PSW eat with the client?", answer: "Yes — many clients prefer a shared meal. It's often the most social part of the day." },
      { question: "Can PSWs prepare meals for multiple days?", answer: "Yes — batch-cook visits are popular. The PSW cooks and portions several meals for the freezer." },
    ],
  },
  "light-housekeeping-services": {
    label: "Light Housekeeping Services",
    category: "aging",
    heroDesc: "Light housekeeping alongside personal care — tidying, laundry, dishes and basic cleaning from a vetted PSW. Keep the home safe and comfortable.",
    intro: "Light housekeeping keeps the client's living space safe, sanitary and comfortable — reducing fall hazards, infections and stress. Our PSWs combine light housekeeping with personal care in the same visit.",
    detail: "This is not a cleaning service — it's home care that includes tidying, laundry and dishes as part of a supportive visit. Deep cleaning is out of scope; the focus is client-centred household maintenance.",
    bullets: [
      "Tidying the client's main living spaces",
      "Kitchen clean-up after meals",
      "Laundry (client's clothing and linens)",
      "Bed making and light bedroom tidying",
      "Bathroom wipe-down for safety",
      "Trash and recycling",
    ],
    faqs: [
      { question: "Is this a cleaning service?", answer: "No — it's home care with light housekeeping included. Deep cleaning, window washing and heavy-duty tasks are out of scope." },
      { question: "Do PSWs do laundry?", answer: "Yes — the client's clothing and linens are washed and folded during the visit." },
      { question: "Can I book only housekeeping without personal care?", answer: "PSW Direct focuses on care visits that include housekeeping. For cleaning-only, we recommend a residential cleaning service." },
    ],
  },
  "transportation-assistance": {
    label: "Transportation Assistance",
    category: "aging",
    heroDesc: "Transportation assistance for seniors — safe escorts to appointments, groceries and community outings, with a PSW at your side.",
    intro: "Transportation assistance keeps seniors mobile and connected. Our PSWs accompany clients to medical appointments, therapy, groceries, banking and social events — safely and reliably.",
    detail: "PSWs accompany clients in the client's own vehicle (with a family driver) or in an accessible taxi/rideshare. For dedicated medical transport with our own drivers, see our Medical Escort service.",
    bullets: [
      "Escort to and from medical appointments",
      "Support during the appointment (note-taking, questions)",
      "Grocery shopping with lift and carry help",
      "Banking, pharmacy and errand runs",
      "Community events and social outings",
      "Waiting-room company",
    ],
    faqs: [
      { question: "Do PSWs drive the client's car?", answer: "PSWs typically do not drive client vehicles. For dedicated door-to-door transport, book our Medical Escort service which includes an insured driver." },
      { question: "Can a PSW stay through the appointment?", answer: "Yes — the PSW waits with the client, takes notes and helps communicate with the clinician." },
      { question: "How long are transport visits?", answer: "Most transport shifts run 2-4 hours to cover travel plus the appointment." },
    ],
  },
  "grocery-shopping-assistance": {
    label: "Grocery Shopping Assistance",
    category: "aging",
    heroDesc: "Grocery shopping assistance from a vetted PSW — plan the list, shop safely and put groceries away. From $35/hr, no contracts.",
    intro: "Grocery shopping assistance keeps pantries stocked and menus varied. Our PSWs plan the shopping list with the client, shop with or for them, and put everything away safely.",
    detail: "For clients who can still shop, the PSW accompanies them and lifts the heavy items. For clients who prefer to stay home, the PSW takes a list and does the shopping directly.",
    bullets: [
      "Meal planning and list preparation",
      "In-store shopping with the client",
      "Solo shopping when the client stays home",
      "Reading labels for dietary needs",
      "Lifting, carrying and putting groceries away",
      "Receipts documented for family review",
    ],
    faqs: [
      { question: "How is the grocery bill handled?", answer: "The client pays for their own groceries — with cash, card or online payment. The PSW brings back a receipt for family records." },
      { question: "Can PSWs use grocery-delivery apps for the client?", answer: "Yes — many clients prefer PSW-supervised online ordering. It's often faster and eliminates the trip." },
      { question: "Can the PSW put the groceries away?", answer: "Yes — the visit typically ends with the groceries put away and the fridge and pantry tidied." },
    ],
  },
  "mobility-assistance": {
    label: "Mobility Assistance",
    category: "aging",
    heroDesc: "In-home mobility assistance from vetted PSWs — safe transfers, walking support and fall prevention. From $35/hr, same-day availability.",
    intro: "Mobility assistance helps clients move safely — from bed to chair, chair to bathroom, and around the home. Our PSWs are trained in transfers, walking support and fall-prevention technique.",
    detail: "Falls are the leading cause of injury and hospitalisation for seniors at home. A regular mobility-assistance visit dramatically reduces the risk — and the anxiety that comes with it.",
    bullets: [
      "Safe transfers (bed, chair, toilet, vehicle)",
      "Walker, cane and wheelchair support",
      "Stair support with proper technique",
      "Fall-prevention scans of the home",
      "Post-fall recovery support",
      "Range-of-motion and gentle mobility encouragement",
    ],
    faqs: [
      { question: "Do PSWs use mechanical lifts?", answer: "Yes — where the equipment is present and the PSW is trained on it. Share the equipment in the home at booking so we match a trained caregiver." },
      { question: "Can PSWs help after a fall?", answer: "Yes — with a doctor's guidance, PSWs help with post-fall mobility, safe transfers and fall-prevention adjustments. If a fall causes injury, always call 911 first." },
      { question: "Can mobility assistance be booked short-term?", answer: "Yes — many families book it for the first few weeks after surgery or a hospital stay, then taper off." },
    ],
  },
};

export const EXPANDED_SERVICE_KEYS = Object.keys(EXPANDED_SERVICE_CONTENT);
