/** Route definitions for /private-home-care-{city} pages */
export const privateHomeCareCityRoutes = [
  { slug: "private-home-care-toronto", city: "Toronto" },
  { slug: "private-home-care-mississauga", city: "Mississauga" },
  { slug: "private-home-care-brampton", city: "Brampton" },
  { slug: "private-home-care-vaughan", city: "Vaughan" },
  { slug: "private-home-care-markham", city: "Markham" },
  { slug: "private-home-care-hamilton", city: "Hamilton" },
  { slug: "private-home-care-ottawa", city: "Ottawa" },
  { slug: "private-home-care-london", city: "London" },
  { slug: "private-home-care-barrie", city: "Barrie" },
  { slug: "private-home-care-richmond-hill", city: "Richmond Hill" },
  { slug: "private-home-care-oakville", city: "Oakville" },
  { slug: "private-home-care-burlington", city: "Burlington" },
  { slug: "private-home-care-kitchener", city: "Kitchener" },
  { slug: "private-home-care-waterloo", city: "Waterloo" },
  { slug: "private-home-care-guelph", city: "Guelph" },
  { slug: "private-home-care-oshawa", city: "Oshawa" },
  { slug: "private-home-care-whitby", city: "Whitby" },
  { slug: "private-home-care-ajax", city: "Ajax" },
  { slug: "private-home-care-pickering", city: "Pickering" },
  { slug: "private-home-care-newmarket", city: "Newmarket" },
  { slug: "private-home-care-aurora", city: "Aurora" },
  { slug: "private-home-care-milton", city: "Milton" },
  { slug: "private-home-care-cambridge", city: "Cambridge" },
  { slug: "private-home-care-windsor", city: "Windsor" },
  { slug: "private-home-care-kingston", city: "Kingston" },
  { slug: "private-home-care-st-catharines", city: "St. Catharines" },
  { slug: "private-home-care-niagara-falls", city: "Niagara Falls" },
  { slug: "private-home-care-peterborough", city: "Peterborough" },
  { slug: "private-home-care-innisfil", city: "Innisfil" },
  { slug: "private-home-care-orillia", city: "Orillia" },
  { slug: "private-home-care-bradford", city: "Bradford" },
  { slug: "private-home-care-alliston", city: "Alliston" },
  { slug: "private-home-care-cobourg", city: "Cobourg" },
  { slug: "private-home-care-belleville", city: "Belleville" },
  { slug: "private-home-care-welland", city: "Welland" },
  { slug: "private-home-care-stoney-creek", city: "Stoney Creek" },
  { slug: "private-home-care-georgetown", city: "Georgetown" },
  { slug: "private-home-care-dundas", city: "Dundas" },
  { slug: "private-home-care-woodstock", city: "Woodstock" },
  { slug: "private-home-care-courtice", city: "Courtice" },
];
