export interface SEORoute {
  slug: string;
  city: string;
}

export const seoRoutes: SEORoute[] = [
  { slug: "home-care-toronto", city: "Toronto" },
  { slug: "psw-toronto", city: "Toronto" },
  { slug: "psw-mississauga", city: "Mississauga" },
  { slug: "psw-brampton", city: "Brampton" },
  { slug: "psw-vaughan", city: "Vaughan" },
  { slug: "psw-markham", city: "Markham" },
  { slug: "psw-richmond-hill", city: "Richmond Hill" },
  { slug: "psw-oakville", city: "Oakville" },
  { slug: "psw-burlington", city: "Burlington" },
  { slug: "psw-ajax", city: "Ajax" },
  { slug: "psw-pickering", city: "Pickering" },
  { slug: "psw-oshawa", city: "Oshawa" },
  { slug: "psw-whitby", city: "Whitby" },
  { slug: "psw-barrie", city: "Barrie" },
  { slug: "psw-hamilton", city: "Hamilton" },
  { slug: "psw-kitchener", city: "Kitchener" },
  { slug: "psw-waterloo", city: "Waterloo" },
  { slug: "psw-cambridge", city: "Cambridge" },
  { slug: "psw-london", city: "London" },
  { slug: "psw-windsor", city: "Windsor" },
  { slug: "psw-st-catharines", city: "St. Catharines" },
  { slug: "psw-niagara-falls", city: "Niagara Falls" },
  { slug: "psw-guelph", city: "Guelph" },
  { slug: "psw-kingston", city: "Kingston" },
  { slug: "psw-peterborough", city: "Peterborough" },
  { slug: "psw-ottawa", city: "Ottawa" },
  { slug: "psw-newmarket", city: "Newmarket" },
  { slug: "psw-aurora", city: "Aurora" },
  { slug: "psw-milton", city: "Milton" },
  { slug: "psw-innisfil", city: "Innisfil" },
  { slug: "psw-orillia", city: "Orillia" },
  { slug: "psw-bradford", city: "Bradford" },
  { slug: "psw-alliston", city: "Alliston" },
  { slug: "psw-cobourg", city: "Cobourg" },
  { slug: "psw-belleville", city: "Belleville" },
  { slug: "psw-welland", city: "Welland" },
  { slug: "psw-stoney-creek", city: "Stoney Creek" },
  { slug: "psw-georgetown", city: "Georgetown" },
  { slug: "psw-dundas", city: "Dundas" },
  { slug: "psw-woodstock", city: "Woodstock" },
  { slug: "psw-courtice", city: "Courtice" },
  // home-care-[city] routes
  { slug: "home-care-mississauga", city: "Mississauga" },
  { slug: "home-care-brampton", city: "Brampton" },
  { slug: "home-care-vaughan", city: "Vaughan" },
  { slug: "home-care-markham", city: "Markham" },
  { slug: "home-care-richmond-hill", city: "Richmond Hill" },
  { slug: "home-care-oakville", city: "Oakville" },
  { slug: "home-care-burlington", city: "Burlington" },
  { slug: "home-care-ajax", city: "Ajax" },
  { slug: "home-care-pickering", city: "Pickering" },
  { slug: "home-care-oshawa", city: "Oshawa" },
  { slug: "home-care-whitby", city: "Whitby" },
  { slug: "home-care-barrie", city: "Barrie" },
  { slug: "home-care-hamilton", city: "Hamilton" },
  { slug: "home-care-kitchener", city: "Kitchener" },
  { slug: "home-care-waterloo", city: "Waterloo" },
  { slug: "home-care-cambridge", city: "Cambridge" },
  { slug: "home-care-london", city: "London" },
  { slug: "home-care-windsor", city: "Windsor" },
  { slug: "home-care-st-catharines", city: "St. Catharines" },
  { slug: "home-care-niagara-falls", city: "Niagara Falls" },
  { slug: "home-care-guelph", city: "Guelph" },
  { slug: "home-care-kingston", city: "Kingston" },
  { slug: "home-care-peterborough", city: "Peterborough" },
  { slug: "home-care-ottawa", city: "Ottawa" },
  { slug: "home-care-newmarket", city: "Newmarket" },
  { slug: "home-care-aurora", city: "Aurora" },
  { slug: "home-care-milton", city: "Milton" },
  { slug: "home-care-innisfil", city: "Innisfil" },
  { slug: "home-care-orillia", city: "Orillia" },
  { slug: "home-care-bradford", city: "Bradford" },
  { slug: "home-care-alliston", city: "Alliston" },
  { slug: "home-care-cobourg", city: "Cobourg" },
  { slug: "home-care-belleville", city: "Belleville" },
  { slug: "home-care-welland", city: "Welland" },
  { slug: "home-care-stoney-creek", city: "Stoney Creek" },
  { slug: "home-care-georgetown", city: "Georgetown" },
  { slug: "home-care-dundas", city: "Dundas" },
  { slug: "home-care-woodstock", city: "Woodstock" },
  { slug: "home-care-courtice", city: "Courtice" },
];
