// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.21.0";

// src/lib/mcp/tools/list_service_areas.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.21.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_service_areas_default = defineTool({
  name: "list_service_areas",
  title: "List service areas",
  description: "Return the cities and service radii currently active for PSW Direct home-care dispatch.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("active_service_radius").select("*").limit(200);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { areas: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/my_bookings.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var my_bookings_default = defineTool2({
  name: "my_bookings",
  title: "My bookings",
  description: "List bookings visible to the signed-in PSW Direct user. RLS scopes the result to the caller (client sees their own, PSW sees assigned, admin sees all).",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 25)."),
    status: z.string().optional().describe("Optional booking status filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    let q = supabase.from("bookings").select(
      "id, booking_code, status, service_type, scheduled_start, scheduled_end, city, created_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { bookings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.21.0";
var whoami_default = defineTool3({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in PSW Direct user identity attached to this MCP session.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail?.() ?? null,
      client_id: ctx.getClientId?.() ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pavibobervhqkfzwkotw";
var mcp_default = defineMcp({
  name: "psw-direct-mcp",
  title: "PSW Direct",
  version: "0.1.0",
  instructions: "Tools for the PSW Direct home-care platform. Callers act as the signed-in user; RLS scopes all reads to what that user is allowed to see. Use `whoami` to confirm identity, `my_bookings` to list bookings visible to the caller, and `list_service_areas` to see active dispatch coverage.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, my_bookings_default, list_service_areas_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.21.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
